create table employees (
	id INT,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	email VARCHAR(50),
	gender VARCHAR(50),
	departnment VARCHAR(50),
	salary VARCHAR(50),
	hire_date DATE
);
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (1, 'Olly', 'Dorward', 'odorward0@amazon.co.uk', 'Male', 'Business Development', '$6197.69', '10.03.2025');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (2, 'Thibaut', 'Tottem', 'ttottem1@i2i.jp', 'Male', 'Research and Development', '$5345.55', '23.10.2024');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (3, 'Henrieta', 'Giovannelli', 'hgiovannelli2@nature.com', 'Bigender', 'Engineering', '$6508.51', '16.10.2020');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (4, 'Janela', 'Cackett', 'jcackett3@npr.org', 'Female', 'Marketing', '$5772.22', '19.04.2023');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (5, 'Miriam', 'Jenkison', 'mjenkison4@mtv.com', 'Female', 'Business Development', '$6828.28', '28.05.2025');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (6, 'Minor', 'Accombe', 'maccombe5@ox.ac.uk', 'Male', 'Marketing', '$6876.04', '17.06.2025');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (7, 'Cynde', 'Strutton', 'cstrutton6@sun.com', 'Female', 'Marketing', '$5344.77', '03.03.2026');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (8, 'Giacinta', 'Wolfenden', 'gwolfenden7@state.tx.us', 'Female', 'Human Resources', '$5989.54', '17.08.2024');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (9, 'Aile', 'Drage', 'adrage8@creativecommons.org', 'Female', 'Accounting', '$6704.61', '27.09.2024');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (10, 'Kissie', 'O'' Brian', 'kobrian9@google.ca', 'Female', 'Services', '$5754.15', '02.07.2020');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (11, 'Erna', 'Regi', 'eregia@fda.gov', 'Female', 'Sales', '$6220.98', '19.10.2024');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (12, 'Raff', 'Ransome', 'rransomeb@topsy.com', 'Male', 'Legal', '$7973.48', '07.10.2022');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (13, 'Gabie', 'Sissland', 'gsisslandc@zdnet.com', 'Female', 'Sales', '$6817.80', '25.12.2023');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (14, 'Arlette', 'Baser', 'abaserd@miitbeian.gov.cn', 'Bigender', 'Training', '$6405.01', '26.11.2022');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (15, 'Guenevere', 'Trendle', 'gtrendlee@hugedomains.com', 'Female', 'Support', '$5837.70', '10.04.2025');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (16, 'Fiorenze', 'Cosans', 'fcosansf@narod.ru', 'Female', 'Product Management', '$6906.38', '01.07.2024');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (17, 'Wendell', 'Pigott', 'wpigottg@woothemes.com', 'Male', 'Services', '$6382.80', '07.03.2022');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (18, 'Maegan', 'Measor', 'mmeasorh@rakuten.co.jp', 'Female', 'Legal', '$6937.33', '03.04.2024');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (19, 'Lion', 'Roscher', 'lroscheri@usda.gov', 'Genderfluid', 'Business Development', '$7842.66', '24.07.2023');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (20, 'Amalie', 'Hillyatt', 'ahillyattj@latimes.com', 'Female', 'Product Management', '$6974.19', '05.10.2025');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (21, 'Erin', 'Luberti', 'elubertik@engadget.com', 'Male', 'Engineering', '$7839.10', '23.05.2022');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (22, 'Paxton', 'Edmead', 'pedmeadl@omniture.com', 'Male', 'Product Management', '$5861.97', '25.09.2020');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (23, 'Rey', 'Petrishchev', 'rpetrishchevm@wiley.com', 'Female', 'Business Development', '$7006.25', '14.01.2025');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (24, 'Darby', 'Livett', 'dlivettn@typepad.com', 'Male', 'Engineering', '$7937.98', '14.03.2024');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (25, 'Lindy', 'Whaplington', 'lwhaplingtono@spiegel.de', 'Male', 'Product Management', '$5284.46', '29.10.2022');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (26, 'Eddi', 'Mitchelson', 'emitchelsonp@youtu.be', 'Female', 'Services', '$5742.39', '14.07.2023');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (27, 'Arlyne', 'Gutridge', 'agutridgeq@yelp.com', 'Female', 'Human Resources', '$5878.70', '29.09.2023');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (28, 'Aldridge', 'Woltering', 'awolteringr@weather.com', 'Non-binary', 'Training', '$6184.84', '21.04.2026');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (29, 'Buddy', 'Benoit', 'bbenoits@imgur.com', 'Male', 'Services', '$7405.27', '23.12.2022');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (30, 'Aidan', 'Donet', 'adonett@goo.gl', 'Female', 'Training', '$7391.29', '28.01.2023');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (31, 'Mychal', 'Verissimo', 'mverissimou@ca.gov', 'Male', 'Product Management', '$7796.55', '07.06.2021');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (32, 'Louis', 'Sleet', 'lsleetv@dagondesign.com', 'Male', 'Support', '$5983.93', '29.01.2022');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (33, 'Zenia', 'Stillgoe', 'zstillgoew@joomla.org', 'Female', 'Accounting', '$6607.70', '18.05.2021');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (34, 'Jeremy', 'Spindler', 'jspindlerx@alibaba.com', 'Agender', 'Product Management', '$6538.21', '01.04.2024');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (35, 'Risa', 'Richarson', 'rricharsony@youtu.be', 'Female', 'Services', '$6418.33', '02.07.2022');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (36, 'Belicia', 'Goeff', 'bgoeffz@scientificamerican.com', 'Female', 'Business Development', '$5327.30', '12.06.2022');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (37, 'Farrell', 'Straffon', 'fstraffon10@illinois.edu', 'Male', 'Services', '$7669.00', '28.12.2023');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (38, 'Flore', 'Pengelley', 'fpengelley11@tamu.edu', 'Female', 'Engineering', '$5834.31', '27.03.2023');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (39, 'Helenka', 'Moretto', 'hmoretto12@shutterfly.com', 'Female', 'Engineering', '$6570.13', '05.01.2026');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (40, 'Caresa', 'Fernley', 'cfernley13@ustream.tv', 'Female', 'Accounting', '$6021.04', '03.09.2021');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (41, 'Natty', 'Niccols', 'nniccols14@apache.org', 'Female', 'Training', '$6508.69', '19.04.2026');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (42, 'Constancy', 'Snasdell', 'csnasdell15@ask.com', 'Female', 'Legal', '$6483.49', '08.10.2021');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (43, 'Annadiana', 'Jelk', 'ajelk16@exblog.jp', 'Female', 'Human Resources', '$5161.71', '09.11.2021');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (44, 'Gan', 'Eccleshare', 'geccleshare17@dmoz.org', 'Male', 'Human Resources', '$5721.00', '07.11.2023');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (45, 'Currie', 'Sher', 'csher18@statcounter.com', 'Non-binary', 'Legal', '$6036.59', '11.09.2022');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (46, 'Tamqrah', 'Baynon', 'tbaynon19@booking.com', 'Female', 'Human Resources', '$6819.46', '17.06.2020');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (47, 'Dorothea', 'McCallion', 'dmccallion1a@studiopress.com', 'Female', 'Marketing', '$5128.79', '02.06.2025');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (48, 'Kaitlyn', 'Domenge', 'kdomenge1b@barnesandnoble.com', 'Female', 'Legal', '$6719.11', '03.06.2025');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (49, 'Gunner', 'Juleff', 'gjuleff1c@unblog.fr', 'Male', 'Sales', '$5034.26', '15.10.2024');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (50, 'Nicolette', 'Parvin', 'nparvin1d@netvibes.com', 'Female', 'Services', '$7663.21', '07.10.2021');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (51, 'Nellie', 'Benjamin', 'nbenjamin1e@bandcamp.com', 'Female', 'Marketing', '$5363.34', '29.11.2021');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (52, 'Robinette', 'Jouannin', 'rjouannin1f@vinaora.com', 'Female', 'Support', '$6982.69', '01.05.2026');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (53, 'Deirdre', 'Welling', 'dwelling1g@walmart.com', 'Female', 'Engineering', '$5389.81', '12.12.2022');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (54, 'Lester', 'MacAree', 'lmacaree1h@reuters.com', 'Male', 'Human Resources', '$7877.47', '10.10.2024');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (55, 'Benny', 'Maskelyne', 'bmaskelyne1i@google.com.hk', 'Male', 'Sales', '$6064.97', '03.02.2022');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (56, 'Bogart', 'Dashkovich', 'bdashkovich1j@comcast.net', 'Male', 'Sales', '$6438.48', '03.04.2023');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (57, 'Rodger', 'Simonel', 'rsimonel1k@usgs.gov', 'Male', 'Engineering', '$7292.17', '20.09.2021');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (58, 'Gilberte', 'Henner', 'ghenner1l@wired.com', 'Female', 'Training', '$7006.65', '15.09.2024');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (59, 'Gwendolyn', 'Caverhill', 'gcaverhill1m@irs.gov', 'Female', 'Legal', '$6438.96', '30.01.2022');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (60, 'Loretta', 'Langhorn', 'llanghorn1n@vk.com', 'Female', 'Business Development', '$5102.04', '27.02.2022');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (61, 'Therine', 'Kundt', 'tkundt1o@state.gov', 'Female', 'Product Management', '$7319.95', '22.01.2022');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (62, 'Mariel', 'Petrello', 'mpetrello1p@alexa.com', 'Female', 'Sales', '$6863.62', '28.11.2024');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (63, 'Cordi', 'Forrest', 'cforrest1q@myspace.com', 'Female', 'Accounting', '$6445.83', '07.08.2023');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (64, 'Lishe', 'Pusill', 'lpusill1r@networkadvertising.org', 'Female', 'Support', '$5398.05', '24.11.2025');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (65, 'Ogden', 'Wooddisse', 'owooddisse1s@over-blog.com', 'Male', 'Business Development', '$6001.36', '30.06.2020');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (66, 'Yettie', 'Arniz', 'yarniz1t@jimdo.com', 'Female', 'Sales', '$7040.11', '04.11.2021');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (67, 'Bertram', 'Leggate', 'bleggate1u@mac.com', 'Male', 'Services', '$7240.37', '28.07.2021');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (68, 'Zacharia', 'Jirousek', 'zjirousek1v@google.it', 'Male', 'Legal', '$7898.96', '30.01.2023');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (69, 'Willyt', 'Nelthropp', 'wnelthropp1w@delicious.com', 'Agender', 'Research and Development', '$7309.71', '19.02.2025');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (70, 'Rustin', 'Crichmer', 'rcrichmer1x@mail.ru', 'Male', 'Training', '$5885.08', '08.02.2022');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (71, 'Meg', 'Snook', 'msnook1y@comsenz.com', 'Female', 'Research and Development', '$7062.51', '03.12.2025');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (72, 'Hermine', 'Dubble', 'hdubble1z@twitter.com', 'Female', 'Sales', '$6413.52', '25.12.2021');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (73, 'Haily', 'Hedin', 'hhedin20@opensource.org', 'Female', 'Training', '$6830.66', '07.08.2021');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (74, 'Sauveur', 'Gosnay', 'sgosnay21@dmoz.org', 'Male', 'Accounting', '$7803.56', '07.05.2026');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (75, 'Steffie', 'Duesbury', 'sduesbury22@cam.ac.uk', 'Female', 'Support', '$7596.80', '11.02.2025');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (76, 'Denis', 'Jeandin', 'djeandin23@huffingtonpost.com', 'Male', 'Business Development', '$5897.01', '21.03.2021');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (77, 'Jeremias', 'Shoemark', 'jshoemark24@ed.gov', 'Male', 'Marketing', '$5333.91', '02.10.2022');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (78, 'Wat', 'Janicek', 'wjanicek25@merriam-webster.com', 'Male', 'Legal', '$6520.58', '25.11.2025');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (79, 'Garvin', 'Shiel', 'gshiel26@nytimes.com', 'Male', 'Training', '$6807.72', '17.12.2021');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (80, 'Kennan', 'Kennifeck', 'kkennifeck27@amazon.co.uk', 'Male', 'Research and Development', '$5884.94', '03.12.2020');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (81, 'Misha', 'Leddie', 'mleddie28@xing.com', 'Female', 'Sales', '$6924.79', '15.04.2026');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (82, 'Lucia', 'Seed', 'lseed29@comcast.net', 'Female', 'Business Development', '$6868.83', '19.01.2023');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (83, 'Merrily', 'Climie', 'mclimie2a@cafepress.com', 'Female', 'Research and Development', '$6294.70', '10.06.2025');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (84, 'Serena', 'Derr', 'sderr2b@live.com', 'Female', 'Product Management', '$6923.83', '08.07.2020');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (85, 'Brig', 'Rominov', 'brominov2c@nih.gov', 'Male', 'Training', '$6949.31', '03.11.2025');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (86, 'Phillipp', 'Fenny', 'pfenny2d@vk.com', 'Male', 'Services', '$5590.35', '14.11.2021');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (87, 'Sadella', 'Ginger', 'sginger2e@umn.edu', 'Genderqueer', 'Legal', '$6456.93', '06.03.2025');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (88, 'Eartha', 'Hardwick', 'ehardwick2f@sitemeter.com', 'Female', 'Business Development', '$5039.72', '25.05.2022');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (89, 'Lorens', 'Melarkey', 'lmelarkey2g@mozilla.com', 'Bigender', 'Services', '$5916.10', '27.10.2025');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (90, 'Tymon', 'McVane', 'tmcvane2h@eventbrite.com', 'Male', 'Research and Development', '$7070.41', '04.04.2021');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (91, 'Archambault', 'Vakhrushev', 'avakhrushev2i@nature.com', 'Male', 'Business Development', '$5183.27', '17.12.2023');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (92, 'Gloriana', 'Seals', 'gseals2j@google.com.hk', 'Female', 'Business Development', '$5889.18', '30.09.2021');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (93, 'Michel', 'Polini', 'mpolini2k@delicious.com', 'Male', 'Support', '$6538.21', '18.05.2025');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (94, 'Dorey', 'Brandreth', 'dbrandreth2l@boston.com', 'Male', 'Marketing', '$7112.80', '18.09.2020');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (95, 'Anallise', 'Portigall', 'aportigall2m@zimbio.com', 'Female', 'Legal', '$7730.63', '05.09.2025');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (96, 'Erastus', 'Cardall', 'ecardall2n@nydailynews.com', 'Male', 'Business Development', '$6043.21', '03.11.2021');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (97, 'Godfry', 'Sein', 'gsein2o@blogger.com', 'Male', 'Support', '$5467.32', '12.06.2025');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (98, 'Elston', 'Capeloff', 'ecapeloff2p@cnbc.com', 'Male', 'Sales', '$5707.31', '27.04.2023');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (99, 'Rosemary', 'Morecomb', 'rmorecomb2q@t.co', 'Female', 'Product Management', '$7244.80', '06.06.2026');
insert into employees (id, first_name, last_name, email, gender, departnment, salary, hire_date) values (100, 'Eziechiele', 'Lalonde', 'elalonde2r@wiley.com', 'Male', 'Services', '$7763.22', '30.10.2020');
